name: Releases

on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker build -t builder .
      - run: git clone --depth=1 --branch mosh-1.3.2 https://github.com/mobile-shell/mosh.git
      - run: docker run -v $PWD/mosh:/mosh -w /mosh --name=builder builder sh -c './autogen.sh && LDFLAGS=-static ./configure && make'
      - uses: actions/upload-artifact@v2
        with:
          name: mosh-server
          path: mosh/src/frontend/mosh-server
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: mosh-client
          path: mosh/src/frontend/mosh-client
          if-no-files-found: error
      - run: |
          (
            echo '- [Build #${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            echo '- [Workflow file](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/.github/workflows/autobuild.yml)'
            echo
            echo '## Files'
            echo '```'
            (cd mosh/src/frontend && file mosh-server mosh-client)
            echo '```'
            echo
            echo '## SHA256 Checksums'
            echo '```'
            (cd mosh/src/frontend && sha256sum mosh-server mosh-client)
            echo '```'
          ) | tee release.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            mosh/src/frontend/mosh-client
            mosh/src/frontend/mosh-server
